
DROP TABLE IF EXISTS `oo_branches`;
CREATE TABLE IF NOT EXISTS `oo_branches` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(128) NOT NULL,
  `DESCRIPTION` varchar(128) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `oo_products`;
CREATE TABLE IF NOT EXISTS `oo_products` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(64) NOT NULL,
  `DESCRIPTION` varchar(128) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `oo_orders`;
CREATE TABLE IF NOT EXISTS `oo_orders` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `USER_ID` int(11) NOT NULL,
  `BRANCH_FK` int(11) NOT NULL,
  `PRODUCT_FK` int(11) NOT NULL,
  `RECV` int(11) NOT NULL,
  `BO_DEL` int(11) NOT NULL,
  `BO_Q` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `BRANCH_ID` (`BRANCH_FK`),
  KEY `PRODUCT_ID` (`PRODUCT_FK`)
) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=latin1;
